### ISSUE TITLE
for a long time, redis-consumer-deployment tries over and over to connect to tf-serving, with tf-serving refusing over and over because max number of connection tries had been exceeded

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-redis-consumer#10]
I've only observed this on AWS, but I suspect it happens on GKE also.

It's worth noting that, once the `tf-serving` pod restarts (which seems to happen once and only once on a lot of our clusters...), `redis-consumer-deployment` is able to connect and no longer gets this error.

This issue was discovered as part of vanvalenlab/kiosk#37.

**Comment by willgraf** [comment]
Are we still seeing this behavior?

**Comment by willgraf** [comment]
The consumer is pinging `tf-serving` but the server is not up yet.  The retries are actually from the interior request library, `urllib3`.

This has been resolved by wrapping the tf-serving requests in a retry loop, retrying all requests that failed with a known re-tryable status.
