### ISSUE TITLE
Add support for larger images

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-redis-consumer#174]
We currently have a hard cap of 2048x2048 for image processing. However, with the recent optimizations to batch processing, I think we can comfortably support larger images. 

Some considerations: What is the current GPU/CPU memory of the instance we're using? Is this shared across workers, or individual for each job? If current memory limits are the bottleneck, is there a substantial price increase for upgrading? Can we decide online based on input image size how much memory needs to be allocated?

**Comment by willgraf** [comment]
We [allocate CPU and memory](https://github.com/vanvalenlab/kiosk-console/blob/44489754902784cba0f2018bad028192d124ebfa/conf/helmfile.d/0260.mesmer-consumer.yaml#L32-L33) consumer beforehand. 

The CPU and memory were not limited by GPU memory but by postprocessing the (rescaled) model outputs. We were already performing something similar to that fix inside the consumer (the consumer doesn't send data to `model.predict`, it sends it to TensorFlow-Serving instead).

**Comment by ngreenwald** [comment]
Okay, so the recent changes won't actually help, it's still the post-processing memory requirements. Totally agree, if it's going to be a substantial ask I don't think it's worth it, only if it would have been an easy change after the most recent PR.
