### ISSUE TITLE
Recent changes to consumer?

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-redis-consumer#197]
Hey all, was there a recent update to the consumer? One of our users is running into issues using the web interface to run Mesmer: https://github.com/angelolab/ark-analysis/issues/587

**Comment by msschwartz21** [comment]
None of the recent changes should have impacted memory capacity of the consumer which seems to be the issue in this case. We have noticed that users have been uploading files that are large enough to bring down pods. We are going to put some safety checks for file size in the near future, but it's not an immediate priority.

**Comment by ngreenwald** [comment]
Is there some shared memory between different jobs? Maybe this was submitted while another job was processing? Something that caused memory to be more bottlenecked than before?
