### ISSUE TITLE
Data is not rescaled before tracking prediction

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk-redis-consumer#59]
Currently data is rescaled in the ImageConsumer to match size of original training data. It is rescaled back to the original size before returning to the tracking consumer. 

It would be easy to rescale data before sending to tracking, but restoring scale to original size will involve modifications to tracking.py where the data is exported.

**Comment by willgraf** [comment]
I'm revisiting some old issues.

I think that it is desirable to track on original-scale data.  We rescale our data for segmentation, and scale it back for tracking.  Can you help me understand why we would want to track on rescaled data?

**Comment by willgraf** [comment]
6 months with no action on this. AFAIK tracking is working fine. I will close this for now and we can reopen it if the issue comes up again.
