### ISSUE TITLE
Consider exporting segmentations from a tracking job before starting tracking

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk-redis-consumer#61]
Currently, if a tracking job crashes, all segmentations are lost. Exporting the segmentations as an intermediate checkpoint could save a lot of time.

Could however be too specific to our needs when we are testing.

**Comment by willgraf** [comment]
Closing this issue since it is over 6 months old and there's been no movement on it. We can reopen it if the need comes up again.
