### ISSUE TITLE
Monitor job url feature

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk-redis-consumer#62]
It would be nice if we could give people a url or something similar to return to if their browser closes or they need to disconnect from the internet. Currently as far as the frontend is concerned, those results would be inaccessible.

Print the job ID on the screen so users can "Monitor Job" or something

**Comment by willgraf** [comment]
This is a good feature idea, but it would really be more of a frontend enhancement than a consumer one.  I've opened another issue there to track progress and will close the issue here.
