### ISSUE TITLE
Drift Correction causes errors in tracked output file movies

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-redis-consumer#67]
Each object (except the first frame) has a series of black lines all over the image.

**Comment by msschwartz21** [comment]
Try calling img_corr.real to see if that resolves the issue

**Comment by willgraf** [comment]
Closing this issue as the offending function has been moved into [`deepcell-toolbox`](https://github.com/vanvalenlab/deepcell-toolbox/issues/6#issue-570922961).
